template: |
  ## Akka Persistence Cassandra $NEXT_PATCH_VERSION Released

  Dear hakkers,

  We are pleased to announce a new patch release of Akka Persistence Cassandra 1.x. This release includes the following changes:

  $CHANGES

  A total of *TODO* issues were closed since *TODO*. The complete list can be found on the *TODO* $NEXT_PATCH_VERSION milestone on GitHub.

  # Credits 

  For this release we had the help of *TODO* committers – thank you all very much!

  *TODO*

  Thanks to [Lightbend](https://www.lightbend.com) for their continued sponsorship of the Akka core team's efforts. Lightbend [offers commercial support](https://www.lightbend.com/lightbend-platform-subscription) for Akka.

  Happy hakking!

  – The Akka Team
